env:
  browser: true
  es2021: true

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  project: ./tsconfig.json
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  - jest
  - jest-dom
  - testing-library
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - airbnb
  - airbnb-typescript
  - prettier
overrides:
  - files:
    - '**/__tests__/**/*.+(ts|tsx|js)'
    - '**/?(*.)+(spec|test).+(ts|tsx|js)'
    extends:
      - plugin:jest/recommended
      - plugin:jest-dom/recommended
      - plugin:testing-library/react
ignorePatterns:
    - vite.config.ts
rules:
  # Reactのインポートをチェックしない
  react/react-in-jsx-scope: off
  # セミコロンつけない
  semi:
    - error
    - never
  # importでエラーでないようにする
  import/extensions: [0, {".js", ".jsx", ".ts", ".tsx"}]
  #debuggerでエラー出さない
  no-debugger: off
  # testing-library/no-debugging-utilsをoff
  testing-library/no-debugging-utils: off