name: post_automate
on:
  workflow_dispatch:
  schedule:
    # 毎日日本時間 07:00,09:00,…,23:00,24:00 に実行 (UTC に変換した時刻)
    - cron: "0 22,0,2,4,6,8,10,12,14,15 * * *"
  push:
    branches: ["main"]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  generate_and_post:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12.10"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python  ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate .env file from Secret
        run: |
          echo "${{ secrets.ENV }}" > .env
          cat .env

      - name: Run Python script
        run: |
          python ./src/main.py

      - name: Read output.txt
        id: read_output
        run: |
          echo "OUTPUT=$(cat ./data/output.txt)" >> $GITHUB_ENV

      - name: Post to Nostr
        uses: snow-actions/nostr@v1.8.1
        with:
          relays: ${{ vars.NOSTR_RELAYS }}
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
          content: ${{ env.OUTPUT }}
        id: publish
      - run: echo "${event}"
        env:
          event: ${{ steps.publish.outputs.event }}
